### PR TITLE
Kai public holiday controller

### LINKED ISSUE #39: Add Holiday Controller and Tests
# Acceptance Criteria:

- [x] There is <tt>HolidayController.java</tt> file in the `src/main/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [x] <tt>HolidayController.java</tt> implements a class that implements an API endpoint that takes in the necessary
      parameters, calls the <tt>HolidayQueryService</tt>, and returns the results.
- [x] The file  <tt>HolidayController.java</tt> file make appropriate use of the
      annotations `@Tag`, `@Operation` and `@Parameter` to document the API.
- [x] The controller endpoint shows up on the Swagger UI page.
- [x] There is a <tt>HolidayControllerTests.java</tt> file in the `src/test/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [x] The tests in <tt>HolidayControllerTests</tt> provide 100% coverage of <tt>HolidayController</tt> for both jacoco and pitest.

# Details

See the assignment description at https://ucsb-cs156.github.io/s24/lab/team01 for details.

### LINKED ISSUE #45: Add Zipcode Controller and Tests
# Acceptance Criteria:

- [x] There is <tt>ZipcodeController.java</tt> file in the `src/main/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [x] <tt>ZipcodeController.java</tt> implements a class that implements an API endpoint that takes in the necessary
      parameters, calls the <tt>ZipcodeQueryService</tt>, and returns the results.
- [x] The file  <tt>ZipcodeController.java</tt> file make appropriate use of the
      annotations `@Tag`, `@Operation` and `@Parameter` to document the API.
- [ ] The controller endpoint shows up on the Swagger UI page.
- [x] There is a <tt>ZipcodeControllerTests.java</tt> file in the `src/test/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] The tests in <tt>ZipcodeControllerTests</tt> provide 100% coverage of <tt>ZipcodeController</tt> for both jacoco and pitest.

# Details

See the assignment description at https://ucsb-cs156.github.io/s24/lab/team01 for details.

### PR DESCRIPTION
**Pull request by kai-maeda**
In this PR, we add an endpoint `/api/publicholiday/get` that can be used to get public holidays for a given year and country.

dev heroku link: http://team01-kai-maeda-dev.dokku-02.cs.ucsb.edu/

closes #39

### CODE REVIEW

**Comment by jchanDev** [comment]
You should make the examples just one country and not multiple.

**Review by kmflippo — APPROVED** [review]
LGTM

**Review by kmflippo — APPROVED** [review]
LGTM

**Review by jchanDev — APPROVED** [review]
LGTM

**Pull request merged**
